<?php

namespace Tests\Unit\Translation;

use App\Translation\PostmarkInboundRecipient;
use Tests\TestCase;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Foundation\Testing\RefreshDatabase;

class PostmarkInboundRecipientTest extends TestCase
{

    /**
     * @var PostmarkInboundRecipient
     */
    private $postmarkRecipient;

    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $json = "{\"Name\": \"John Dough\", \"Email\": \"john@example.com\"}";
        $this->postmarkRecipient = new PostmarkInboundRecipient($json);
    }

    /**
     * @test
     */
    public function it_instantiates_from_json_string()
    {
        $this->assertInstanceOf(PostmarkInboundRecipient::class, $this->postmarkRecipient);
    }

    /**
     * @test
     */
    public function it_gets_the_email()
    {
        $this->assertEquals("john@example.com", $this->postmarkRecipient->email());
    }

    /**
     * @test
     */
    public function it_gets_the_name()
    {
        $this->assertEquals("John Dough", $this->postmarkRecipient->name());
    }



}
